// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: asr_engine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AsrEngine_LoadModel_FullMethodName        = "/asrengine.AsrEngine/LoadModel"
	AsrEngine_UnloadModel_FullMethodName      = "/asrengine.AsrEngine/UnloadModel"
	AsrEngine_StartJob_FullMethodName         = "/asrengine.AsrEngine/StartJob"
	AsrEngine_StopJob_FullMethodName          = "/asrengine.AsrEngine/StopJob"
	AsrEngine_GetJobStatus_FullMethodName     = "/asrengine.AsrEngine/GetJobStatus"
	AsrEngine_StreamJobStatus_FullMethodName  = "/asrengine.AsrEngine/StreamJobStatus"
	AsrEngine_ListLoadedModels_FullMethodName = "/asrengine.AsrEngine/ListLoadedModels"
	AsrEngine_GetEngineInfo_FullMethodName    = "/asrengine.AsrEngine/GetEngineInfo"
)

// AsrEngineClient is the client API for AsrEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsrEngineClient interface {
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*StopJobResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatus, error)
	StreamJobStatus(ctx context.Context, in *StreamJobStatusRequest, opts ...grpc.CallOption) (AsrEngine_StreamJobStatusClient, error)
	ListLoadedModels(ctx context.Context, in *ListLoadedModelsRequest, opts ...grpc.CallOption) (*ListLoadedModelsResponse, error)
	GetEngineInfo(ctx context.Context, in *GetEngineInfoRequest, opts ...grpc.CallOption) (*GetEngineInfoResponse, error)
}

type asrEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAsrEngineClient(cc grpc.ClientConnInterface) AsrEngineClient {
	return &asrEngineClient{cc}
}

func (c *asrEngineClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, AsrEngine_LoadModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrEngineClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, AsrEngine_UnloadModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrEngineClient) StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, AsrEngine_StartJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrEngineClient) StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*StopJobResponse, error) {
	out := new(StopJobResponse)
	err := c.cc.Invoke(ctx, AsrEngine_StopJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrEngineClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, AsrEngine_GetJobStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrEngineClient) StreamJobStatus(ctx context.Context, in *StreamJobStatusRequest, opts ...grpc.CallOption) (AsrEngine_StreamJobStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &AsrEngine_ServiceDesc.Streams[0], AsrEngine_StreamJobStatus_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &asrEngineStreamJobStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AsrEngine_StreamJobStatusClient interface {
	Recv() (*JobStatus, error)
	grpc.ClientStream
}

type asrEngineStreamJobStatusClient struct {
	grpc.ClientStream
}

func (x *asrEngineStreamJobStatusClient) Recv() (*JobStatus, error) {
	m := new(JobStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *asrEngineClient) ListLoadedModels(ctx context.Context, in *ListLoadedModelsRequest, opts ...grpc.CallOption) (*ListLoadedModelsResponse, error) {
	out := new(ListLoadedModelsResponse)
	err := c.cc.Invoke(ctx, AsrEngine_ListLoadedModels_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrEngineClient) GetEngineInfo(ctx context.Context, in *GetEngineInfoRequest, opts ...grpc.CallOption) (*GetEngineInfoResponse, error) {
	out := new(GetEngineInfoResponse)
	err := c.cc.Invoke(ctx, AsrEngine_GetEngineInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsrEngineServer is the server API for AsrEngine service.
// All implementations must embed UnimplementedAsrEngineServer
// for forward compatibility
type AsrEngineServer interface {
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error)
	StopJob(context.Context, *StopJobRequest) (*StopJobResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatus, error)
	StreamJobStatus(*StreamJobStatusRequest, AsrEngine_StreamJobStatusServer) error
	ListLoadedModels(context.Context, *ListLoadedModelsRequest) (*ListLoadedModelsResponse, error)
	GetEngineInfo(context.Context, *GetEngineInfoRequest) (*GetEngineInfoResponse, error)
	mustEmbedUnimplementedAsrEngineServer()
}

// UnimplementedAsrEngineServer must be embedded to have forward compatible implementations.
type UnimplementedAsrEngineServer struct {
}

func (UnimplementedAsrEngineServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedAsrEngineServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedAsrEngineServer) StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartJob not implemented")
}
func (UnimplementedAsrEngineServer) StopJob(context.Context, *StopJobRequest) (*StopJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopJob not implemented")
}
func (UnimplementedAsrEngineServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedAsrEngineServer) StreamJobStatus(*StreamJobStatusRequest, AsrEngine_StreamJobStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamJobStatus not implemented")
}
func (UnimplementedAsrEngineServer) ListLoadedModels(context.Context, *ListLoadedModelsRequest) (*ListLoadedModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLoadedModels not implemented")
}
func (UnimplementedAsrEngineServer) GetEngineInfo(context.Context, *GetEngineInfoRequest) (*GetEngineInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEngineInfo not implemented")
}
func (UnimplementedAsrEngineServer) mustEmbedUnimplementedAsrEngineServer() {}

// UnsafeAsrEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsrEngineServer will
// result in compilation errors.
type UnsafeAsrEngineServer interface {
	mustEmbedUnimplementedAsrEngineServer()
}

func RegisterAsrEngineServer(s grpc.ServiceRegistrar, srv AsrEngineServer) {
	s.RegisterService(&AsrEngine_ServiceDesc, srv)
}

func _AsrEngine_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrEngineServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrEngine_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrEngineServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsrEngine_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrEngineServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrEngine_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrEngineServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsrEngine_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrEngineServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrEngine_StartJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrEngineServer).StartJob(ctx, req.(*StartJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsrEngine_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrEngineServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrEngine_StopJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrEngineServer).StopJob(ctx, req.(*StopJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsrEngine_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrEngineServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrEngine_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrEngineServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsrEngine_StreamJobStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamJobStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AsrEngineServer).StreamJobStatus(m, &asrEngineStreamJobStatusServer{stream})
}

type AsrEngine_StreamJobStatusServer interface {
	Send(*JobStatus) error
	grpc.ServerStream
}

type asrEngineStreamJobStatusServer struct {
	grpc.ServerStream
}

func (x *asrEngineStreamJobStatusServer) Send(m *JobStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _AsrEngine_ListLoadedModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoadedModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrEngineServer).ListLoadedModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrEngine_ListLoadedModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrEngineServer).ListLoadedModels(ctx, req.(*ListLoadedModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsrEngine_GetEngineInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEngineInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrEngineServer).GetEngineInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrEngine_GetEngineInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrEngineServer).GetEngineInfo(ctx, req.(*GetEngineInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AsrEngine_ServiceDesc is the grpc.ServiceDesc for AsrEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsrEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asrengine.AsrEngine",
	HandlerType: (*AsrEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadModel",
			Handler:    _AsrEngine_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _AsrEngine_UnloadModel_Handler,
		},
		{
			MethodName: "StartJob",
			Handler:    _AsrEngine_StartJob_Handler,
		},
		{
			MethodName: "StopJob",
			Handler:    _AsrEngine_StopJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _AsrEngine_GetJobStatus_Handler,
		},
		{
			MethodName: "ListLoadedModels",
			Handler:    _AsrEngine_ListLoadedModels_Handler,
		},
		{
			MethodName: "GetEngineInfo",
			Handler:    _AsrEngine_GetEngineInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobStatus",
			Handler:       _AsrEngine_StreamJobStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "asr_engine.proto",
}
