run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - goconst
    - gocyclo
    - revive

linters-settings:
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    rules:
      - name: exported
        disabled: true # distinct relaxation for existing codebases
      - name: package-comments
        disabled: true
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  
  gocyclo:
    # minimal code complexity to report, 30 by default (but we want it slightly stricter but still sane)
    min-complexity: 25

  goconst:
    # minimal length of string constant, 3 by default
    min-len: 3
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 3

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gocyclo
        - errcheck

  # Independent of default exclusions, we can relax some common annoyances
  # default is to use a default set of exclusions. we can keep that.
