FROM python:3.10-slim AS build_pyannote
RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg libsndfile1 && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir pyannote.audio


FROM python:3.10-slim
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

ARG POCKETBASE_ADMIN_EMAIL
ARG POCKETBASE_ADMIN_PASSWORD
ARG SCRIBO_FILES
ARG REDIS_HOST
ARG REDIS_PORT
ARG OPENAI_API_KEY
ARG OPENAI_ENDPOINT="https://api.openai.com/v1"
ARG OPENAI_MODEL="gpt-4"
ARG OPENAI_ROLE="system"
ARG POCKETBASE_VERSION=0.22.21

ENV POCKETBASE_ADMIN_EMAIL=$POCKETBASE_ADMIN_EMAIL
ENV POCKETBASE_ADMIN_PASSWORD=$POCKETBASE_ADMIN_PASSWORD
ENV SCRIBO_FILES=$SCRIBO_FILES
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV OPENAI_ENDPOINT=$OPENAI_ENDPOINT
ENV OPENAI_MODEL=$OPENAI_MODEL
ENV OPENAI_ROLE=$OPENAI_ROLE
ENV BODY_SIZE_LIMIT=512M

COPY --from=build_pyannote /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=build_pyannote /usr/local/bin /usr/local/bin

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    ffmpeg \
    unzip \
    libgd3 \
    libmad0 \
    libid3tag0 \
    libboost-all-dev \
    libboost-filesystem-dev \
    libboost-program-options-dev \
    libboost-regex-dev \
    curl \
    pkg-config \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*



RUN ARCH="$(dpkg --print-architecture)" && \
    case "${ARCH}" in \
      "amd64") ARCH_URL="https://github.com/bbc/audiowaveform/releases/download/1.10.1/audiowaveform_1.10.1-1-12_amd64.deb" ;; \
      "arm64") ARCH_URL="https://github.com/bbc/audiowaveform/releases/download/1.10.1/audiowaveform_1.10.1-1-12_arm64.deb" ;; \
      *) echo "Unsupported architecture"; exit 1 ;; \
    esac && \
    wget ${ARCH_URL} -O audiowaveform.deb && \
    dpkg -i audiowaveform.deb && \
    apt-get -f install -y && \
    rm audiowaveform.deb

# Download and unzip PocketBase
RUN ARCH="$(dpkg --print-architecture)" && \
    curl -L "https://github.com/pocketbase/pocketbase/releases/download/v${POCKETBASE_VERSION}/pocketbase_${POCKETBASE_VERSION}_linux_${ARCH}.zip" -o /tmp/pb.zip && \
    unzip /tmp/pb.zip pocketbase -d /usr/local/bin/ && \
    rm /tmp/pb.zip


RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && apt-get install -y nodejs
