name: Main Docker Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
          
      - name: Extract version from tag
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=$(date +'%Y%m%d-%H%M%S')
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push CPU Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/aken-2019/scriberr_ll:${{ steps.version.outputs.version }}
            ghcr.io/aken-2019/scriberr_ll:latest

      - name: Verify multi-platform image
        run: |
          docker buildx imagetools inspect ghcr.io/aken-2019/scriberr_ll:${{ steps.version.outputs.version }}
          docker buildx imagetools inspect ghcr.io/aken-2019/scriberr_ll:latest
