name: nightly-docker

on:
  push:
    branches:
      - nightly  # Only trigger on pushes to the nightly branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push scriberr:nightly Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/rishikanthc/scriberr:nightly

      - name: Verify multi-platform image for scriberr:nightly
        run: |
          docker buildx imagetools inspect ghcr.io/rishikanthc/scriberr:nightly
