name: Nightly CUDA Docker Build

on:
  pull_request:
    types: [closed]
    branches:
      - nightly

jobs:
  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CUDA nightly image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./Dockerfile-cuda128
          tags: |
            ghcr.io/rishikanthc/scriberr:nightly-cuda128

      - name: Verify multi-platform image
        run: |
          docker buildx imagetools inspect ghcr.io/rishikanthc/scriberr:nightly-cuda128